language: "php"

php:
  - "7.1.14"
before_script:
  - "curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar"
  - "composer install"
script:
- "phpunit --configuration=phpunit.xml --coverage-text"