language: php
php:
  - 7.1.14
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true